### ISSUE TITLE
Issue with driver loading

### ISSUE THREAD

**Issue by tHEO2k17** [jilenloa/botman_ussd_codeigniter#1]
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>An uncaught Exception was encountered</h4>

<p>Type: Error</p>
<p>Message: Call to a member function driver() on null</p>
<p>Filename: /Users/tHEO/Workspace/Taxi Check/botman_ussd_codeigniter/application/controllers/Ussd.php</p>
<p>Line Number: 26</p>

	<p>Backtrace:</p>
	
		
	
		
			<p style="margin-left:10px">
			File: /Users/tHEO/Workspace/Taxi Check/botman_ussd_codeigniter/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	

</div>

**Comment by jilenloa** [comment]
I need a more detailed stack trace. Check your applications/logs folder check if you find the error there.
My line 26 of Ussd.php on my side is a comment block.

**Comment by tHEO2k17** [comment]
> I need a more detailed stack trace. Check your applications/logs folder check if you find the error there.
> My line 26 of Ussd.php on my side is a comment block.


<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>An uncaught Exception was encountered</h4>

<p>Type: Error</p>
<p>Message: Call to a member function driver() on null</p>
<p>Filename: /Users/tHEO/Workspace/Taxi Check/botman_ussd_codeigniter/application/controllers/Ussd.php</p>
<p>Line Number: 26</p>


	<p>Backtrace:</p>
	
		
	
		
			<p style="margin-left:10px">
			File: /Users/tHEO/Workspace/Taxi Check/botman_ussd_codeigniter/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	

</div>

**Comment by jilenloa** [comment]
check your line 26 of Ussd.php and tell me what it is in code

**Comment by tHEO2k17** [comment]
> check your line 26 of Ussd.php and tell me what it is in code

$this->load->driver('cache');

**Comment by jilenloa** [comment]
That's line 38 of mine. Paste the entire Ussd.php here

**Comment by tHEO2k17** [comment]
> That's line 38 of mine. Paste the entire Ussd.php here

<?php

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Cache\CodeIgniterCache;
use BotMan\BotMan\Drivers\DriverManager;

defined('BASEPATH') OR exit('No direct script access allowed');

class Ussd extends CI_Controller {

	function __construct()
	{
		header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
		
	}

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see https://codeigniter.com/user_guide/general/urls.html
	 */
	public function index()
	{
        DriverManager::loadDriver(HubtelBotmanDriver::class);

        $config = [
            //Your driver-specific configuration
            "hubtel" => [
                "client_key" => "TOKEN" //demo configuration
            ]
        ];

        $this->load->driver('cache');
        // cache is needed to maintain states
        // $this->cache->file refers to the file system cache driver
        $botman = BotManFactory::create($config, new CodeIgniterCache($this->cache->file));

        $botman->on(HubtelBotmanDriver::NEW_SESSION, function($payload, $bot) {
            /** @var BotMan $bot */
            $user_info = $bot->getUser()->getInfo();
            $bot->startConversation(new DemoConversation());
        });

        $botman->listen();
	}
}

**Comment by tHEO2k17** [comment]
> That's line 38 of mine. Paste the entire Ussd.php here

i had to add cors headers

**Comment by jilenloa** [comment]
something is wrong. It's like you are not sending me the Ussd class. Is that all the contents of Ussd.php?

**Comment by tHEO2k17** [comment]
> something is wrong. It's like you are not sending me the Ussd class. Is that all the contents of Ussd.php?

`<?php

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Cache\CodeIgniterCache;
use BotMan\BotMan\Drivers\DriverManager;

defined('BASEPATH') OR exit('No direct script access allowed');

class Ussd extends CI_Controller {

	function __construct()
	{
		header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
		
	}

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see https://codeigniter.com/user_guide/general/urls.html
	 */
	public function index()
	{
        DriverManager::loadDriver(HubtelBotmanDriver::class);

        $config = [
            //Your driver-specific configuration
            "hubtel" => [
                "client_key" => "TOKEN" //demo configuration
            ]
        ];

        $this->load->driver('cache');
        // cache is needed to maintain states
        // $this->cache->file refers to the file system cache driver
        $botman = BotManFactory::create($config, new CodeIgniterCache($this->cache->file));

        $botman->on(HubtelBotmanDriver::NEW_SESSION, function($payload, $bot) {
            /** @var BotMan $bot */
            $user_info = $bot->getUser()->getInfo();
            $bot->startConversation(new DemoConversation());
        });

        $botman->listen();
	}
}
`

**Comment by jilenloa** [comment]
this is a codeigniter issue. $this in this context is CI_Controller.

**Comment by tHEO2k17** [comment]
> this is a codeigniter issue. $this in this context is CI_Controller.

WhatsApp?

**Comment by jilenloa** [comment]
my phone is off currently

> > this is a codeigniter issue. $this in this context is CI_Controller.
> 
> WhatsApp?

**Comment by tHEO2k17** [comment]
> my phone is off currently
> 
> > > this is a codeigniter issue. $this in this context is CI_Controller.
> > 
> > 
> > WhatsApp?

ok

**Comment by jilenloa** [comment]
i am on skype

**Comment by tHEO2k17** [comment]
> > my phone is off currently
> > > > this is a codeigniter issue. $this in this context is CI_Controller.
> > > 
> > > 
> > > WhatsApp?
> 
> ok

that

> i am on skype

that works

**Comment by jilenloa** [comment]
Please make sure you add this in your Ussd constructor
`parent::__construct();`

**Comment by tHEO2k17** [comment]
> parent::__construct();

Great
